#############################################################################
# Makefile for building: mediacute
# Generated by qmake (2.01a) (Qt 4.7.4) on: dim. avr. 29 21:25:31 2012
# Project:  mediacute.pro
# Template: app
# Command: /usr/bin/qmake-qt4 QMAKE_CC\ =\ cc QMAKE_CXX\ =\ g++ QMAKE_CFLAGS_RELEASE\ =\ \ -g\ -O2\ -g\ -O2\ -Wall QMAKE_CXXFLAGS_RELEASE\ =\ \ -g\ -O2\ -g\ -O2\ -Wall -o Makefile mediacute.pro
#############################################################################

####### Compiler, tools and options

CC            = cc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -O2 -g -O2 -Wall -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -O2 -g -O2 -Wall -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/phonon -I/usr/include/qt4 -I/usr/include/qt4/phonon_compat -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lphonon -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		dialogopen.cpp \
		dialogscript.cpp moc_mainwindow.cpp \
		moc_dialogopen.cpp \
		moc_dialogscript.cpp \
		qrc_data.cpp
OBJECTS       = main.o \
		mainwindow.o \
		dialogopen.o \
		dialogscript.o \
		moc_mainwindow.o \
		moc_dialogopen.o \
		moc_dialogscript.o \
		qrc_data.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		mediacute.pro
QMAKE_TARGET  = mediacute
DESTDIR       = 
TARGET        = mediacute

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_dialogopen.h ui_dialogscript.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mediacute.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) QMAKE_CC\ =\ cc QMAKE_CXX\ =\ g++ QMAKE_CFLAGS_RELEASE\ =\ \ -g\ -O2\ -g\ -O2\ -Wall QMAKE_CXXFLAGS_RELEASE\ =\ \ -g\ -O2\ -g\ -O2\ -Wall -o Makefile mediacute.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) QMAKE_CC\ =\ cc QMAKE_CXX\ =\ g++ QMAKE_CFLAGS_RELEASE\ =\ \ -g\ -O2\ -g\ -O2\ -Wall QMAKE_CXXFLAGS_RELEASE\ =\ \ -g\ -O2\ -g\ -O2\ -Wall -o Makefile mediacute.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mediacute1.0.0 || $(MKDIR) .tmp/mediacute1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mediacute1.0.0/ && $(COPY_FILE) --parents mainwindow.h dialogopen.h dialogscript.h .tmp/mediacute1.0.0/ && $(COPY_FILE) --parents data.qrc .tmp/mediacute1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp dialogopen.cpp dialogscript.cpp .tmp/mediacute1.0.0/ && $(COPY_FILE) --parents mainwindow.ui dialogopen.ui dialogscript.ui .tmp/mediacute1.0.0/ && (cd `dirname .tmp/mediacute1.0.0` && $(TAR) mediacute1.0.0.tar mediacute1.0.0 && $(COMPRESS) mediacute1.0.0.tar) && $(MOVE) `dirname .tmp/mediacute1.0.0`/mediacute1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mediacute1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_dialogopen.cpp moc_dialogscript.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_dialogopen.cpp moc_dialogscript.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_dialogopen.cpp: dialogopen.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogopen.h -o moc_dialogopen.cpp

moc_dialogscript.cpp: dialogscript.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialogscript.h -o moc_dialogscript.cpp

compiler_rcc_make_all: qrc_data.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_data.cpp
qrc_data.cpp: data.qrc \
		Quran.xml \
		icons/48x48/mediacute.png
	/usr/bin/rcc -name data data.qrc -o qrc_data.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dialogopen.h ui_dialogscript.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dialogopen.h ui_dialogscript.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_dialogopen.h: dialogopen.ui
	/usr/bin/uic-qt4 dialogopen.ui -o ui_dialogopen.h

ui_dialogscript.h: dialogscript.ui
	/usr/bin/uic-qt4 dialogscript.ui -o ui_dialogscript.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		dialogopen.h \
		dialogscript.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

dialogopen.o: dialogopen.cpp dialogopen.h \
		ui_dialogopen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogopen.o dialogopen.cpp

dialogscript.o: dialogscript.cpp dialogscript.h \
		ui_dialogscript.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogscript.o dialogscript.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dialogopen.o: moc_dialogopen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogopen.o moc_dialogopen.cpp

moc_dialogscript.o: moc_dialogscript.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogscript.o moc_dialogscript.cpp

qrc_data.o: qrc_data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_data.o qrc_data.cpp

####### Install

install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_PROGRAM) /home/kovax/elkirtasse-group/mediacute/mediacute_1.0/mediacute.desktop $(INSTALL_ROOT)/usr/share/applications/
	-strip $(INSTALL_ROOT)/usr/share/applications/mediacute.desktop


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/mediacute.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_icon48: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/ 
	-$(INSTALL_FILE) /home/kovax/elkirtasse-group/mediacute/mediacute_1.0/icons/48x48/mediacute.png $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/


uninstall_icon48:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/mediacute.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/ 


install_icon128: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ 
	-$(INSTALL_FILE) /home/kovax/elkirtasse-group/mediacute/mediacute_1.0/icons/128x128/mediacute.png $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/


uninstall_icon128:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/mediacute.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/128x128/apps/ 


install:  install_desktopfile install_target install_icon48 install_icon128  FORCE

uninstall: uninstall_desktopfile uninstall_target uninstall_icon48 uninstall_icon128   FORCE

FORCE:

